from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict, List

from .common import safe_dict, safe_list, safe_str


DWG_UNSUPPORTED_STATUS = "unsupported_no_native_writer"
DWG_EXTERNAL_CONVERSION_STATUS = "external_conversion_hook_configured_review_only"
DWG_EXTERNAL_CONVERSION_UNVERIFIED_STATUS = "external_conversion_hook_configured_unverified"


DWG_PROVIDER_OPTIONS: List[Dict[str, Any]] = [
    {
        "provider": "Autodesk Platform Services Design Automation",
        "path_type": "external_conversion_service",
        "license_owner": "customer_or_operator",
        "integration_notes": [
            "Run a configured AutoCAD/Civil 3D activity outside Civora.",
            "Convert Civora DXF/LandXML review artifacts to DWG in the provider environment.",
            "Attach a workflow record with tool version, activity ID, source artifact hash, and result.",
        ],
        "civora_native_support": False,
    },
    {
        "provider": "ODA Drawings SDK",
        "path_type": "licensed_sdk_candidate",
        "license_owner": "customer_or_operator",
        "integration_notes": [
            "Requires a separate SDK license and deployment review.",
            "Could write or convert DWG through an adapter after legal and technical validation.",
            "Needs regression fixtures for layer names, units, blocks, surfaces, and pipe-network exchange.",
        ],
        "civora_native_support": False,
    },
    {
        "provider": "RealDWG",
        "path_type": "licensed_autodesk_sdk_candidate",
        "license_owner": "customer_or_operator",
        "integration_notes": [
            "Requires Autodesk licensing and a supported runtime environment.",
            "Could become a native writer only after implementation and repeatable compatibility tests.",
            "Civil 3D object fidelity would still require a target workflow record.",
        ],
        "civora_native_support": False,
    },
    {
        "provider": "Manual CAD workstation workflow",
        "path_type": "operator_conversion",
        "license_owner": "customer_or_operator",
        "integration_notes": [
            "Open the review DXF/LandXML in the operator's CAD environment.",
            "Save DWG externally and attach a workflow record back to Civora.",
            "Civora treats the attached result as external evidence, not as native DWG generation.",
        ],
        "civora_native_support": False,
    },
]


DWG_CAPABILITY_MATRIX: Dict[str, Dict[str, Any]] = {
    "dxf_review_export": {
        "format": "DXF",
        "native_writer": True,
        "import_supported": False,
        "export_supported": True,
        "review_ready_when": "current export audit passes",
        "status": "audited_review_export",
        "preservation_contract": {
            "layers": "locally_parse_verified",
            "object_types": "locally_parse_verified_for_supported_entities",
            "blocks_symbols": "placeholder_entities_preserved_when_exported",
            "text_labels": "locally_parse_verified",
            "dimensions": "verified_where_supported_by_exporter",
            "canonical_ids": "sidecar_and_entity_metadata_traceability_required",
        },
        "verification_scope": "Civora DXF export -> local parse -> Civora contract checks",
        "notes": "Primary CAD review artifact generated by Civora; still a review artifact unless externally accepted.",
    },
    "landxml_exchange": {
        "format": "LandXML",
        "native_writer": True,
        "import_supported": True,
        "export_supported": True,
        "review_ready_when": "pipe-network contract exists and current export audit passes",
        "workflow_states": ["not_verified", "blocked_needs_review", "externally_verified_review_only"],
        "status": "not_verified",
        "notes": "Exchange path for surfaces/pipe-network metadata; target workflow evidence is still needed.",
    },
    "civil3d_native_package": {
        "format": "Civil 3D",
        "native_writer": False,
        "import_supported": False,
        "export_supported": False,
        "review_ready_when": "external workflow record is attached for a target Civil 3D workflow",
        "workflow_states": ["not_verified", "blocked_needs_review", "externally_verified_review_only"],
        "required_workflow_record_fields": [
            "verifier_identity",
            "verification_date",
            "tool",
            "tool_version",
            "source_artifact_hashes",
            "import_result",
            "observed_limitations",
        ],
        "status": "not_verified",
        "notes": "Civora does not generate a native Civil 3D package.",
    },
    "dwg_native": {
        "format": "DWG",
        "native_writer": False,
        "import_supported": False,
        "export_supported": False,
        "review_ready_when": "not available without a real writer or external conversion hook",
        "status": DWG_UNSUPPORTED_STATUS,
        "notes": "Civora does not write DWG natively.",
    },
    "dwg_external_conversion": {
        "format": "DWG",
        "native_writer": False,
        "import_supported": False,
        "export_supported": False,
        "review_ready_when": "configured converter plus external workflow record",
        "status": "optional_hook_not_configured",
        "opt_in_required": True,
        "review_only": True,
        "notes": "Optional architecture only; no native DWG writing is claimed without a licensed/provider hook and external workflow record.",
    },
}


def dwg_conversion_hook_from_meta(meta: Dict[str, Any]) -> Dict[str, Any]:
    """Normalize optional DWG conversion-hook metadata without claiming DWG support."""

    raw = (
        safe_dict(meta.get("dwg_conversion_hook"))
        or safe_dict(safe_dict(meta.get("external_conversion_hooks")).get("dwg"))
        or safe_dict(safe_dict(meta.get("cad_interop")).get("dwg_conversion_hook"))
    )
    provider = safe_str(raw.get("provider"))
    enabled = bool(raw.get("enabled") is True and provider)
    source_formats = [
        safe_str(item).lower()
        for item in safe_list(raw.get("source_formats") or raw.get("inputs"))
        if safe_str(item)
    ]
    if not source_formats:
        source_formats = ["dxf", "landxml"] if enabled else []
    return {
        "enabled": enabled,
        "provider": provider,
        "hook_id": safe_str(raw.get("hook_id") or raw.get("id")),
        "source_formats": source_formats,
        "requires_external_workflow_record": True,
        "native_dwg_writer": False,
        "status": "configured" if enabled else "not_configured",
    }


def dwg_external_workflow_record(meta: Dict[str, Any]) -> Dict[str, Any]:
    external = safe_dict(meta.get("external_verification"))
    record = (
        safe_dict(external.get("dwg_conversion"))
        or safe_dict(external.get("dwg"))
        or safe_dict(meta.get("dwg_external_conversion_record"))
        or safe_dict(meta.get("dwg_external_verification"))
    )
    return record


def dwg_strategy_from_meta(meta: Dict[str, Any]) -> Dict[str, Any]:
    hook = dwg_conversion_hook_from_meta(meta)
    record = dwg_external_workflow_record(meta)
    record_result = safe_str(record.get("result")).lower()
    record_present = bool(record)
    record_passed = record_result in {"passed", "pass", "ok", "completed", "success"}
    if hook["enabled"] and record_passed:
        dwg_status = DWG_EXTERNAL_CONVERSION_STATUS
        review_ready = True
    elif hook["enabled"]:
        dwg_status = DWG_EXTERNAL_CONVERSION_UNVERIFIED_STATUS
        review_ready = False
    else:
        dwg_status = DWG_UNSUPPORTED_STATUS
        review_ready = False

    matrix = deepcopy(DWG_CAPABILITY_MATRIX)
    matrix["dwg_external_conversion"].update(
        {
            "export_supported": bool(hook["enabled"] and record_passed),
            "status": dwg_status if hook["enabled"] else "optional_hook_not_configured",
            "provider": hook["provider"],
            "workflow_record_present": record_present,
        }
    )
    return {
        "source": "dwg_compatibility_strategy_v1",
        "native_dwg_supported": False,
        "dwg_export_supported": bool(hook["enabled"] and record_passed),
        "dwg_native_export_supported": False,
        "dwg_external_conversion_review_artifact_available": bool(hook["enabled"] and record_passed),
        "dwg_review_ready": review_ready,
        "dwg_status": dwg_status,
        "dwg_unsupported_reason": (
            "Civora has no native DWG writer. DWG requires a licensed SDK/provider implementation or an external conversion hook with a workflow record."
        ),
        "civil3d_requirement": (
            "For Civil 3D, use DXF/LandXML review artifacts plus a target-workflow record showing the tool/version, imported source hashes, and observed limitations."
        ),
        "conversion_hook": hook,
        "external_workflow_record_present": record_present,
        "external_workflow_record": deepcopy(record),
        "capability_matrix": matrix,
        "provider_options": deepcopy(DWG_PROVIDER_OPTIONS),
        "ui_message": (
            "DWG is not exported natively. Use DXF/LandXML review artifacts, or configure an external DWG conversion hook and attach a workflow record."
        ),
        "truth_label": "DWG remains unsupported natively; optional conversion metadata never means Civora wrote or verified a DWG file.",
    }


__all__ = [
    "DWG_CAPABILITY_MATRIX",
    "DWG_PROVIDER_OPTIONS",
    "DWG_UNSUPPORTED_STATUS",
    "dwg_strategy_from_meta",
    "dwg_conversion_hook_from_meta",
    "dwg_external_workflow_record",
]
